#include "bmf-vm.h"

void bmfBoot() {
    outer(": last (l) @ ;");
    outer(": here (h) @ ;");
    outer(": inline    ( -- ) $40 last cell + c! ;");
    outer(": immediate ( -- ) $80 last cell + c! ;");
    outer(": cells  ( n--n' ) cell * ; inline");
    outer(": ->code ( off--addr ) cells mem + ;");
    outer(": code@  ( off--dw )  ->code @ ;");
    outer(": code!  ( dw off-- ) ->code ! ;");
    outer(": , ( dw-- ) here dup 1 + (h) ! code! ;");
    // outer("");
    outer(": bye      ( -- ) 999 state ! ;");
    outer(": (exit)   ( --n )  0 ; inline");
    outer(": (lit)    ( --n )  1 ; inline");
    outer(": (jmp)    ( --n )  2 ; inline");
    outer(": (jmpz)   ( --n )  3 ; inline");
    outer(": (jmpnz)  ( --n )  4 ; inline");
    outer(": (njmpz)  ( --n )  5 ; inline");
    outer(": (njmpnz) ( --n )  6 ; inline");
    outer(": (ztype)  ( --n ) 48 ; inline");
    // outer("");
    outer(": if   (jmpz)   , here 0 , ; immediate");
    outer(": -if  (njmpz)  , here 0 , ; immediate");
    outer(": if0  (jmpnz)  , here 0 , ; immediate");
    outer(": -if0 (njmpnz) , here 0 , ; immediate");
    outer(": then here swap code!     ; immediate");
    // outer("");
    outer(": begin here ; immediate");
    outer(": again (jmp)     , , ; immediate");
    outer(": while (jmpnz)   , , ; immediate");
    outer(": -while (njmpnz) , , ; immediate");
    outer(": until (jmpz)    , , ; immediate");
    // outer("");
    outer("( val and (val) define a very efficient variable mechanism )");
    outer("( Usage:  val a@   (val) (a)   : a! (xx) ! ; )");
    outer(": const ( n-- ) add-word (lit) , , (exit) , ;");
    outer(":  val  ( -- ) 0 const ;");
    outer(": (val) ( -- ) here 2 - ->code const ;");
    // outer("");
    outer("mem mem-sz + const dict-end");
    outer("32 ->code const (vh)");
    outer("64 1024 * ->code const vars");
    outer("vars (vh) !");
    outer(": vhere ( --a ) (vh) @ ;");
    outer(": allot ( n-- ) (vh) +! ;");
    outer(": var   ( n-- ) vhere const allot ;");
    // outer("");
    outer("( 3 variables that can be used as locals - x,y,z )");
    outer(": +L1 ( x -- )    +L x! ;");
    outer(": +L2 ( x y-- )   +L y! x! ;");
    outer(": +L3 ( x y z-- ) +L z! y! x! ;");
    // outer("");
    outer(": x++ ( -- )  x@+ drop ;  : x--  ( -- )  x@ 1- x! ;  : x@-  ( --n ) x@ x-- ;");
    outer(": c@x ( --b ) x@ c@ ;     : c@x+ ( --b ) x@+ c@ ;    : c@x- ( --b ) x@- c@ ;");
    outer(": c!x ( b-- ) x@ c! ;     : c!x+ ( b-- ) x@+ c! ;    : c!x- ( b-- ) x@- c! ;");
    // outer("");
    outer(": y++ ( -- )  y@+ drop ;  : y--  ( -- )  y@ 1- y! ;  : y@-  ( --n ) y@ y-- ;");
    outer(": c@y ( --b ) y@ c@ ;     : c@y+ ( --b ) y@+ c@ ;    : c@y- ( --b ) y@- c@ ;");
    outer(": c!y ( b-- ) y@ c! ;     : c!y+ ( b-- ) y@+ c! ;    : c!y- ( b-- ) y@- c! ;");
    // outer("");
    outer(": z++ ( -- )  z@+ drop ;  : z--  ( -- )  z@ 1- z! ;  : z@-  ( --n ) z@ z-- ;");
    outer(": c@z ( --b ) z@ c@ ;     : c@z+ ( --b ) z@+ c@ ;    : c@z- ( --b ) z@- c@ ;");
    outer(": c!z ( b-- ) z@ c! ;     : c!z+ ( b-- ) z@+ c! ;    : c!z- ( b-- ) z@- c! ;");
    // outer("");
    outer("( Strings )");
    outer(": compiling? ( --n ) state @ 1 = ;");
    outer(": (\") ( --a ) +L vhere dup z! x! 1 >in +!");
    outer("    begin");
    outer("        >in @ c@ y! 1 >in +!");
    outer("        y@ 0 = y@ '\"' = or");
    outer("        if  0 c!x+  z@");
    outer("            compiling? if (lit) , , x@ (vh) ! then");
    outer("            -L exit");
    outer("        then");
    outer("        y@ c!x+");
    outer("    again ;");
    // outer("");
    outer(": z\" ( \"string\"--addr ) (\") ; immediate");
    outer(": .\" ( \"string\"-- ) (\") compiling? if (ztype) , exit then ztype ; immediate");
    // outer("");
    outer("( More core words )");
    outer(": [ ( -- ) 0 state ! ; immediate  ( 0 = INTERPRET )");
    outer(": ] ( -- ) 1 state ! ;            ( 1 = COMPILE )");
    outer(": rdrop ( -- ) r> drop ; inline");
    outer(": tuck  ( a b--b a b )   swap over ; inline");
    outer(": nip   ( a b--b )       swap drop ; inline");
    outer(": ?dup ( n--n n|0 )  -if dup then ;");
    outer(": 2dup  ( a b--a b a b ) over over ; inline");
    outer(": 2drop ( a b-- )        drop drop ; inline");
    outer(": -rot ( a b c--c a b )  swap >r swap r> ;");
    outer(": cell+ ( a--a' ) cell + ; inline");
    outer(": 0< ( n--f ) 0 <    ; inline");
    outer(": <= ( a b--f ) > 0= ;");
    outer(": >= ( a b--f ) < 0= ;");
    outer(": type ( a n-- ) for dup c@ emit 1+ next drop ;");
    outer(": btwi ( n l h--f ) >r over <= swap r> <= and ;");
    outer(": negate ( n--n' ) 0 swap - ;");
    outer(": abs ( n--n' ) dup 0< if negate then ;");
    outer(": cr  ( -- )     13 emit 10 emit ;");
    outer(": tab ( -- )      9 emit ;");
    outer(": space  ( -- )  32 emit ;");
    outer(": spaces ( n-- ) for space next ;");
    outer(": /   ( a b--q ) /mod nip  ;");
    outer(": mod ( a b--r ) /mod drop ;");
    outer(": */  ( n m q--n' ) >r * r> / ;");
    outer(": unloop  ( -- ) (lsp) @ 3 - 0 max (lsp) ! ;");
    outer(": execute ( xt-- ) ?dup if >r then ;");
    outer(": decimal  ( -- )  #10 base ! ;");
    outer(": hex      ( -- )  $10 base ! ;");
    outer(": binary   ( -- )  %10 base ! ;");
    // outer("");
    outer("   1 var (neg)");
    outer("  65 var buf");
    outer("cell var (buf)");
    outer(": ?neg ( n--n' ) dup 0< dup (neg) c! if negate then ;");
    outer(": hold ( c-- )   -1 (buf) +! (buf) @ c! ;");
    outer(": #.   ( -- )    '.' hold ;");
    outer(": #n   ( n-- )   '0' + dup '9' > if 7 + then hold ;");
    outer(": #    ( n--m )  base @ /mod swap #n ;");
    outer(": #s   ( n--0 )  # -if #s exit then ;");
    outer(": <#   ( n--n' ) ?neg buf 65 + (buf) ! 0 hold ;");
    outer(": #>   ( n--a )  drop (neg) @ if '-' hold then (buf) @ ;");
    outer(": (.)  ( n-- )   <# #s #> ztype ;");
    outer(": .    ( n-- )   (.) space ;");
    // outer("");
    outer(": 0sp 0 (sp) ! ;");
    outer(": depth ( --n ) (sp) @ 1- ;");
    outer(": .s '(' emit space depth ?dup if");
    outer("        stk swap for cell+ dup @ . next drop");
    outer("    then ')' emit ;");
    // outer("");
    outer(": .word ( de-- ) cell+ 2 + ztype ;");
    outer(": words ( -- ) +L last x! 0 y! 0 z! begin");
    outer("        x@ dict-end < if0 '(' emit z@ . .\" words)\" -L exit then");
    outer("        x@ .word tab z++");
    outer("        x@ cell+ 1+ c@ 7 > if y++ then");
    outer("        y@+ 12 > if cr 0 y! then");
    outer("        x@ de-sz + x!");
    outer("    again ;");
    // outer("");
    outer(": words-n ( n-- ) +L last x! 0 y! for");
    outer("        x@ .word tab");
    outer("        y@+ 12 > if cr 0 y! then");
    outer("		x@ de-sz + x!");
    outer("    next -L ;");
    // outer("");
    outer("cell var t4   cell var t5");
    outer(": [[ here t4 !  vhere t5 !  1 state ! ;");
    outer(": ]] (exit) , 0 state ! t4 @ dup >r (h) ! t5 @ (vh) ! ; immediate");
    // outer("");
    outer("cell var t4   cell var t5   cell var t6");
    outer(": marker ( -- ) here t4 !   vhere t5 !   last t6 ! ;");
    outer(": forget ( -- ) t4 @ (h) !  t5 @ (vh) !  t6 @ (l) ! ;");
    // outer("");
    outer("( Strings / Memory )");
    outer(": pad    ( --a ) vhere $100 + ;");
    outer(": fill   ( a num ch-- ) -rot for 2dup c! 1+ next 2drop ;");
    outer(": s-end  ( str--end ) dup s-len + ;   ( end: address of the null )");
    outer(": s-cpy  ( dst src--dst ) 2dup s-len 1+ cmove ;");
    outer(": s-cat  ( dst src--dst ) over s-end  over s-len 1+  cmove ;");
    outer(": s-catc ( dst ch--dst )  over s-end  +L1  c!x+  0 c!x+  -L ;");
    outer(": s-catn ( dst num--dst ) <# #s #> s-cat ;");
    outer(": s-scat ( src dst--dst ) swap s-cat ;");
    outer(": s-eqn  ( s1 s2 n--f ) +L3 z@ for c@x+ c@y+ = if0 -L 0 unloop exit then next -L 1 ;");
    outer(": s-eq   ( s1 s2--f ) dup s-len 1+ s-eqn ;");
    // outer("");
    outer("( Disk: 1024 blocks, 1024 bytes each )");
    outer(": kb ( n--m ) 1024 * ;");
    outer(": mb ( n--m ) kb kb ;");
    outer("mem 14 mb + const disk");
    outer("32 var fn");
    outer("val blk@   (val) t0");
    outer(": #blks     ( --n )   1024 ;");
    outer(": blk-sz    ( --n )   1024 ;");
    outer(": blk!      ( n-- )   0 max #blks 1- min t0 ! ;");
    outer(": blk-addr  ( n--a )  blk-sz * disk + ;");
    outer(": blk-clr   ( n-- )   blk-addr blk-sz 0 fill ;");
    outer(": blk-read  ( n-- )   dup blk-addr read ;");
    outer(": blk-write ( n-- )   dup blk-addr write ;");
    outer(": load      ( n-- )   blk-addr outer ;");
    outer(": load-next ( n-- )   blk-addr >in ! ;");
    outer("( [[ #blks for i blk-read next ]] )");
    outer(": si .\" last=\" (l) @ hex . .\" dict-end=\" mem mem-sz + . .\" here=\" here . cr decimal ;");
    outer("marker si");
}